sudo: required
services:
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t mittalvaibhav1/client-test ./client

script:
  - docker run -e CI=true  mittalvaibhav1/client-test npm run test -- --coverage

after_success:
  - docker build -t mittalvaibhav1/multi-client ./client
  - docker build -t mittalvaibhav1/multi-nginx ./nginx
  - docker build -t mittalvaibhav1/multi-server ./client
  - docker build -t mittalvaibhav1/multi-workers ./workers
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mittalvaibhav1/multi-client
  - docker push mittalvaibhav1/multi-nginx
  - docker push mittalvaibhav1/multi-server
  - docker push mittalvaibhav1/multi-workers