version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - 5000:5000
        volumes: 
            - /app/node_modules
            - ./server:/app

        
