version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGHOST=postgres
            - PGPORT=5432
            - PGUSER=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
        depends_on: 
            - redis
            - postgres
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./client:/app
        depends_on: 
            - redis
            - postgres
            - api
            - worker
    worker:
        build:
            context: ./workers
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
            - api
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - '8080:80'
        depends_on: 
            - redis
            - postgres
            - api
            - worker
            - client


        
